
= Impetus for Integrating ActivityPub

ActivityPub integration is an exciting prospect because it could remove
a significant barrier to groups connecting to the Fediverse:
presently, connecting a group to the Fediverse requires
a technical team to set up and administer an instance.
With this bridge, a small group could get online with the ease of an invitation to a chat group.

Visibility of Holochain to the Fediverse is also a primary impetus,
demonstrating the utility of using a DHT in the context of decentralized web-based protocols.

Value alignment between Holochain and Fediverse participants may be reified in this solution which serves both communities.
Where people wish to avoid Big Tech in social media and group chat,
the Holochain network cuts out dependence on any data center.

== Design Goals WRT Impetus

The target for this integration is for people to easily create,
or follow an invitation to,
to a MewsFeed group with a similar user experience to following an invite link to a Discord server or Signal group.
Once connected to a MewsFeed DHT people may participate in the whole Fediverse.

The group would *collectively* administer and *serve* an instance.
Administration would be optional,
but everyone will have the same top-level privileges,
necessitating some level of trust between members,
which means this solution is not recommended for large communities where many people don't know each other;
while exception could be made for ephemeral,
or throw-away communication channels where the risks are acceptable,
they must be aware the design is highly vulnerable to *social engineering* attacks.

== use cases

=== Group Sessions Such as Conference Talks

At a presentation the presenter or facilitator may begin with a QR code to join a MewsFeed DHT, and seed a hashtag for Q&A, and the public may follow notes, photos, and all such posts from everyone in the room.
The conversations may be continued at the end of the session.
Participants need not expose personal information to be identified as having been present.

A college class, or any congruent social construct, such as a concert, could follow this story.

=== coordination and connection ahead of events

A whole conference or other large event like a music festival could invite ticket holders
to a MewsFeed DHT when sales close.
Visibility constraints, such as defaulting to _DHT-only_ posts,
would allow participants to coordinate connections, make travel arrangements,
and share important information, and after, photos and memories.

Beyond the utility of information and communication,
in this story the event producer gives attendees a way to *identify* to the world their membership.

=== clubs & other chat groups

MewsFeed could act as a drop-in replacement for chat in any kind of group context,
with the added benefit of being able to publish to the web and communicate with the rest of the Fediverse.

== Holochain visibility

All of these uses of MewsFeed would generate awareness of Holochain and p2p technology,
shifting public opinion to understand and demand the appropriate technology for their needs,
and leading to trying other software built on Holochain.
